# Used to specify where the deployment is being done
cloudProvider: "dev"
cloudProviderRegion: "dev-region"
serviceInternalName: "ltv-service"
skaffold: false

storageDB: 
  size : 2000Gi
  storageClass : local-path
storageWIJ: 
  size: 50Gi
  storageClass : local-path
storageJournal1: 
  size: 2000Gi
  storageClass : local-path
storageJournal2: 
  size: 2000Gi
  storageClass : local-path

compute:
  database:
    nodeTypeSelector: ""
    cpu: 4
    memory: 512Mi
  frontend:
    nodeTypeSelector: ""
    cpu: 4
    memory: 512Mi

mirrored: false
image:
  registry: containers.intersystems.com/iscinternal/sds/demo_ltv
  backend:
    repository: ltv_service
  frontend:
    repository: ltv_frontend

# These are the secret fields needed to successfully deploy.
# They will be injected by the control plane:
requiredSecrets:
  irisLicense: ""
  intersystemsContainerRegistrySecret: ""

kafkaBroker: b-1.sds-fs-occ.o5d16i.c2.kafka.us-east-2.amazonaws.com:9092

# Amir: Feb/2021
# In the future, we need to see how we can secure the ingress with TLS
ingress:
  enabled: true
  host: localhost
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

superServer:
  enabled: "false"
  hostname: "localhost"
  port: "10000"

management:
  enabled: "false"
  hostname: "localhost"
  port: "10001"

ui:
  enabled: "false"
  hostname: "localhost"
  port: "10002"

