apiVersion: v1
kind: Service
metadata:
  name: service-iris-tunnel
  namespace: {{ .Release.Name }}
spec:
  selector:
    intersystems.com/component: data
    intersystems.com/kind: IrisCluster
    intersystems.com/role: iris
  ports:
    - port: 52773
      targetPort: 52773