apiVersion: apps/v1
kind: Deployment
metadata:
  name: ltv-frontend
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ltv-frontend
  template:
    metadata:
      labels:
        app: ltv-frontend
    spec:   
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      
      containers:
      - name: ltv-frontend
        resources:
          requests:              
            cpu: {{ .Values.compute.frontend.cpu }}
            memory: {{ .Values.compute.frontend.memory }}

        {{- if eq .Values.skaffold true }}
        image: {{ .Values.frontend.skaffoldImage }}
        {{- else }}
        image: {{ .Values.image.registry }}/{{ .Values.image.frontend.repository }}:{{ .Chart.AppVersion }}
        {{- end }}
        ports:
          - containerPort: 4200

      {{- if .Values.compute.frontend.nodeTypeSelector }}
      nodeSelector:
        sds/node-type: {{ .Values.compute.frontend.nodeTypeSelector }}
      {{- end }}
          

      tolerations:
      - key: sds/select-worker
        value: select-worker
        effect: NoSchedule